### ISSUE TITLE
Publish styles as separate scss files to allow for easy customization 

### ISSUE THREAD

**Issue by beeman** [angular-split/angular-split#248]
In the current version of this library, the styles are part of `SplitComponent`.

While this is great for a usability point of view (no need to include a separate style) it limits the flexibility.

To offer a greater flexibility to developers using this library, it makes sense to publish the styles as separate SCSS files.

Pros
- makes it easier to extend/override the styles.
- publishing it as SCSS allows for using variables, making it easy to tweak appearance.
- we can provide with various styles out of the box (dark/light).

Cons
- Installation takes 1 more step as the user has to include the style. 

## TODO

- [ ] pull out styles into separate file, making sure it still works.
- [ ] add SCSS variables for colors.
- [ ] get rid of any `ng-deep`, where possible.

**Comment by Harpush** [comment]
@beeman I have an idea how to tackle it... Let me know your opinion and if anything is missing:
1. SCSS theme globally:
```scss
@use 'angular-splitter/theme' as split;

@include split.core();
@include split.theme((
  gutter-background-color: #eeeeee
  // More here?
));
```
2. Specific CSS variables overriding:
```scss
--as-split-gutter-background-color: #eeeeee;
// More here?
```
3. Allowing custom icons as template (Related to #163, #227, #266):
```html
<as-split ...>
  <div *asSplitGutterIcon>...</div>
  ...
</as-split>
```
The `asSplitGutterIcon` context will be:
```ts
interface SplitGutterIconTemplateContext {
  areaBefore: IArea
  areaAfter: IArea
  index: number
}
```
All that's missing is knowing programmatically (if needed) when a gutter is being dragged through `asSplitGutterIcon` context as currently it is only in the "css land".
